[[redirects]]
  from = "/index.html"
  to = "/*"
  status = 200

[[redirects]]
  from = "/"
  to = "https://hellorusk.net/"
  status = 200

[[redirects]]
  from = "/whoami"
  to = "https://hellorusk.net/whoami"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"